language: php
php:
  - 5.4
  - 5.5 
  - 5.6
  - 7
  - hhvm 

before_script:
  - composer selfupdate
  - composer update --dev --prefer-source --no-interaction $PREFER_LOWEST

script:
  - phpunit --coverage-clover=coverage.clover 
