language: php

services:
  - docker

matrix:

jobs:
  fast_finish: true
  allow_failures:
      - php: 7.2
      - php: hhvm
      - php: nightly
  include:
    - # test
    - stage: Test
      php: 7.1
      before_script:
        - phpenv config-rm xdebug.ini
        - composer selfupdate
        - composer install --no-interaction
      script:
        - ./vendor/bin/phpunit
    - # test
    - stage: Test
      php: 7.2
      before_script:
        - phpenv config-rm xdebug.ini
        - composer selfupdate
        - composer update --no-interaction
      script:
        - ./vendor/bin/phpunit
    - # test
    - stage: Test
      php: hhvm
      before_script:
        - phpenv config-rm xdebug.ini
        - composer selfupdate
        - composer update --no-interaction
      script:
        - ./vendor/bin/phpunit
    - # test
    - stage: Test
      php: nightly
      before_script:
        - phpenv config-rm xdebug.ini
        - composer selfupdate
        - composer update --no-interaction
      script:
        - ./vendor/bin/phpunit

    - stage: Integration
      php: 7.1
      before_script:
        - phpenv config-rm xdebug.ini
        - docker run -it -d -p 8080:8080 crossbario/crossbar
        - composer selfupdate
        - composer install --no-interaction
      script:
        - ./vendor/bin/phpunit --configuration ./phpunit.integration.xml.dist

    - # publish
    - stage: Coverage
      php: 7.1
      before_script:
        - composer selfupdate
        - composer install --no-interaction
        - docker run -it -d -p 8080:8080 crossbario/crossbar
      script:
        - phpdbg -qrr phpunit --coverage-clover=coverage.clover
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - php vendor/bin/codacycoverage clover coverage.clover

