language: php
php:
  - 5.6
  - 7
  - hhvm 

before_script:
  - composer selfupdate
  - composer update --dev --prefer-source --no-interaction $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover 
after_success:
  - bash <(curl -s https://codecov.io/bash)
