language: php
php:
  - 7.1
  - 7.2
  - hhvm
  - nightly

services:
  - docker

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.2
        - php: hhvm
        - php: nightly

jobs:
  include:
    - # test
    - stage: test
      before_script:
        - composer selfupdate
        - composer update --no-interaction
      script:
        - ./vendor/bin/phpunit
    - # publish
    - stage: publish
      php: 7.1
      before_script:
        - composer selfupdate
        - composer install --no-interaction
        - docker run -it -d -p 8080:8080 crossbario/crossbar
      script:
        - ./vendor/bin/phpunit --coverage-clover=coverage.clover
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - php vendor/bin/codacycoverage clover coverage.clover

before_script:
  - composer selfupdate
  - composer update --no-interaction