language: php
php:
  - 7.1
  - 7.2
  - hhvm
  - nightly

services:
  - docker

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.2
        - php: hhvm
        - php: nightly

before_install:
  - docker run -it -d -p 8080:8080 crossbario/crossbar

before_script:
  - composer selfupdate
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpunit --configuration ./phpunit.integration.xml.dist
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover coverage.clover
